"""empty message

Revision ID: 11915e90e68b
Revises: 7a2867c212bd
Create Date: 2024-02-27 18:00:03.919053

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '11915e90e68b'
down_revision = '7a2867c212bd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('items', schema=None) as batch_op:
        batch_op.alter_column('price',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=2),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('items', schema=None) as batch_op:
        batch_op.alter_column('price',
               existing_type=sa.Float(precision=2),
               type_=sa.REAL(),
               existing_nullable=False)

    # ### end Alembic commands ###
